name: CI

on:
  push:
      branches: [ master, dev]
  pull_request_target:
    branches: [ master, dev]

jobs:
  tox:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9' ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tox-logs
          retention-days: 30
          path: |
            .tox
            .coverage
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: Run tox
        run: |
          tox

  build:
    needs:
      - tox
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag netprox:$(date +%s)